const UI={
 en:{brandName:'Mohamed Salaheldin',brandRole:'Independent Business & Project Advisor',eyebrow:'Guided Advisory Service Explorer',heroTitle:'Find the real gap.<br><span>See what can help.</span>',heroText:'Choose your organization type and the problem you are actually facing. The explorer shows the first services most relevant to the situation - not a catalogue of everything I can do.',start:'Start the diagnostic',browse:'Browse the service library',profilePdf:'View profile PDF',framework:'Gap-to-Action Framework™',frameworkPromise:'Diagnose the gap. Solve the live case. Transfer the method.',years:'Years of cross-functional experience',stepOne:'Step 1',who:'Who are you?',whoSub:'Choose the organization type so the recommendations reflect the way your business or project actually works.',step1Title:'Your organization',step1Sub:'Choose one role.',step2Title:'Your pressure point',step2Sub:'Choose what is happening now.',step3Title:'First actions',step3Sub:'See 3-5 services to consider first.',stepTwo:'Step 2',happening:'What is happening?',happeningSub:'Choose the description closest to the current situation. You can change it at any time.',recommended:'Recommended First Actions',startOver:'Start over',seeRelated:'See the full service library',signatureLabel:'Signature Service',signatureTitle:'Interactive Advisory Workshops & Live Problem-Solving Labs',signatureText:'Not lectures. Your team brings a real tender, negotiation, pricing, procurement, supply-chain or workflow case, and the session is used to diagnose it, challenge assumptions, build the solution and agree the next actions.',diagnose:'Diagnose',challenge:'Challenge',solve:'Solve',act:'Act',discussLab:'Discuss a live workshop',libraryKicker:'Full Capability Library',libraryTitle:'Looking for a specific service or problem?',librarySub:'Search by the service, the problem or the outcome. The guided diagnostic above remains the fastest route.',footerBrand:'Mohamed Salaheldin Advisory',footerLine:'Senior expertise for the critical points where businesses and projects lose time, cost, control and opportunity.',struggle:'What you may be struggling with',change:'What will change',details:'Scope & details',discuss:'Discuss this need',email:'Email',allCats:'All categories',search:'Search services, problems or outcomes',showing:'Showing {shown} of {total} services',showMore:'Show more ({remaining} remaining)',noResults:'No matching services found.'},
 ar:{brandName:'محمد صلاح الدين',brandRole:'مستشار مستقل للأعمال والمشروعات',eyebrow:'مستكشف تفاعلي للخدمات الاستشارية',heroTitle:'حدد المشكلة الحقيقية.<br><span>وشوف إيه اللي ممكن يساعدك.</span>',heroText:'اختَر نوع جهتك والمشكلة التي تواجهها فعليًا. ستظهر لك أولًا الخدمات الأقرب للحالة، بدل ما تتوه في قائمة طويلة من كل ما يمكن تقديمه.',start:'ابدأ التشخيص',browse:'استعرض مكتبة الخدمات',profilePdf:'عرض البروفايل PDF',framework:'منهج الفجوة إلى الإجراء™',frameworkPromise:'نحدد الخلل، نحل الحالة الفعلية، وننقل طريقة التعامل معها.',years:'سنة من الخبرة المتكاملة',stepOne:'الخطوة 1',who:'ما طبيعة جهتك؟',whoSub:'اختيار نوع الجهة يساعد على إظهار الخدمات الأقرب لطريقة عملك ومشكلتك الفعلية.',step1Title:'نوع الجهة',step1Sub:'اختَر جهة واحدة.',step2Title:'المشكلة الحالية',step2Sub:'اختَر ما يحدث عندك الآن.',step3Title:'أول خطوات مقترحة',step3Sub:'تظهر لك 3 إلى 5 خدمات تستحق النظر أولًا.',stepTwo:'الخطوة 2',happening:'ما المشكلة التي تواجهها؟',happeningSub:'اختَر الوصف الأقرب للوضع الحالي، ويمكنك تغييره في أي وقت.',recommended:'أول خدمات تستحق النظر',startOver:'ابدأ من جديد',seeRelated:'استعرض مكتبة الخدمات الكاملة',signatureLabel:'خدمة مميزة',signatureTitle:'ورش استشارية تفاعلية ومختبرات مباشرة لحل مشكلات العمل',signatureText:'ليست محاضرات. يحضر الفريق منافسة أو تسعيرًا أو تفاوضًا أو مشكلة مشتريات أو إجراءً فعليًا من شغله، ونستخدم الجلسة لتشخيص المشكلة ومناقشة الافتراضات وبناء الحل وتحديد خطوات التنفيذ.',diagnose:'شخّص',challenge:'ناقش',solve:'حل',act:'نفّذ',discussLab:'ناقش ورشة عملية',libraryKicker:'مكتبة القدرات والخدمات',libraryTitle:'تبحث عن خدمة أو مشكلة محددة؟',librarySub:'ابحث باسم الخدمة أو المشكلة أو النتيجة. ويظل التشخيص بالأعلى هو الطريق الأسرع للوصول لما يناسب حالتك.',footerBrand:'محمد صلاح الدين للاستشارات العملية',footerLine:'خبرة قيادية عند النقاط التي تخسر فيها الشركات والمشروعات الوقت أو التكلفة أو السيطرة أو الفرص.',struggle:'المشكلة التي قد تكون عندك',change:'ما الذي سيتغير؟',details:'نطاق الخدمة والتفاصيل',discuss:'ناقش هذا الاحتياج',email:'بريد إلكتروني',allCats:'كل المجالات',search:'ابحث بالخدمة أو المشكلة أو النتيجة',showing:'عرض {shown} من أصل {total} خدمة',showMore:'عرض المزيد ({remaining} متبقية)',noResults:'لا توجد نتائج مطابقة.'},
 both:{}
};
const ROLES={consultant:{en:['Consultant','Capacity gaps, proposal pressure and project-delivery support.'],ar:['مكتب استشاري','ضغط في الأحمال أو نقص خبرة متخصصة أو دعم مطلوب في العروض والمشروعات.'],icon:'C'},contractor:{en:['Contractor / EPC','Bids, procurement, contracts, delays and project recovery.'],ar:['مقاول / EPC','تحديات المنافسات والمشتريات والعقود والتأخير واستعادة مسار المشروع.'],icon:'E'},owner:{en:['Owner / Developer','Visibility, contractor control, investment and project decisions.'],ar:['مالك / مطور','الحاجة لرؤية مستقلة وسيطرة أقوى على المقاول والقرارات والاستثمار.'],icon:'O'},factory:{en:['Factory / Industrial','Supply chain, inventory, process and capability pressure points.'],ar:['مصنع / منشأة صناعية','مشكلات سلسلة الإمداد والمخزون والإجراءات والقدرات الداخلية.'],icon:'F'}};
const CHALLENGES={bids:{en:['Bids & Margin','We keep losing bids, pricing risk badly, or winning work that hurts margin.'],ar:['المنافسات وهامش الربح','نخسر منافسات، أو نسعّر المخاطر بشكل غير كافٍ، أو نفوز بأعمال تضع هامش الربح تحت ضغط.']},procurement:{en:['Procurement & Long-Lead','Materials, suppliers or long-lead items are starting to control the programme.'],ar:['المشتريات والمواد طويلة التوريد','المواد أو الموردون أو البنود طويلة التوريد بدأت تتحكم في برنامج المشروع.']},commercial:{en:['Cash Flow, Contracts & Claims','Cash, contract exposure, variations or claims are getting harder to control.'],ar:['السيولة والعقود والمطالبات','السيولة أو الالتزامات التعاقدية أو التغييرات أو المطالبات أصبحت أصعب في السيطرة.']},delay:{en:['Delay & Recovery','The project is slipping and current recovery actions are not changing the result.'],ar:['التأخير واستعادة المسار','المشروع يتأخر وإجراءات استعادة المسار الحالية لا تغيّر النتيجة.']},technical:{en:['Technical Office Backlog','Submittals, RFIs or engineering deliverables are blocking progress.'],ar:['تراكم أعمال المكتب الفني','الاعتمادات أو RFIs أو المخرجات الهندسية بدأت تعطل تقدم التنفيذ.']},risk:{en:['Risk & Exposure','Important risks are being discovered late or without effective mitigation.'],ar:['المخاطر والآثار المحتملة','المخاطر المهمة تُكتشف متأخرة أو من غير إجراءات عملية تقلل أثرها.']},process:{en:['Processes & Digital Gaps','Work depends on individuals, disconnected departments or manual workflows.'],ar:['الإجراءات والتحول الرقمي','العمل يعتمد على أفراد، أو الإدارات منفصلة، أو الإجراءات اليدوية تعطل الأداء.']},capacity:{en:['Capability & Workload','The team is overloaded or missing senior / specialist capability.'],ar:['نقص الخبرة وضغط العمل','الفريق محمل بأكثر من طاقته أو يفتقد خبرة قيادية أو تخصصية في نقطة حرجة.']},'owner-control':{en:['Owner Control & Visibility','You need an independent view of what is actually happening in the project.'],ar:['رقابة المالك ووضوح الصورة','تحتاج رأيًا مستقلًا يوضح ما يحدث فعليًا بالمشروع بعيدًا عن التقارير الشكلية.']},cost:{en:['Cost & Value','Costs are rising and cost-cutting is not producing real value.'],ar:['التكلفة والقيمة','التكلفة ترتفع بينما إجراءات خفض المصروفات لا تحقق قيمة حقيقية أو مستدامة.']},investment:{en:['Feasibility & Investment','The technical and commercial case is not clear enough for a confident decision.'],ar:['الجدوى وقرار الاستثمار','الجانب الفني والتجاري غير واضح بما يكفي لاتخاذ قرار استثماري مطمئن.']}};
const ROLE_CHALLENGES={consultant:['bids','capacity','commercial','technical','risk','delay','process'],contractor:['bids','procurement','commercial','delay','technical','risk','cost','process'],owner:['owner-control','delay','commercial','risk','cost','investment','procurement','technical'],factory:['procurement','commercial','risk','cost','process','capacity','investment']};
let DATA=null,lang=localStorage.getItem('msa_lang')||((navigator.language||'').toLowerCase().startsWith('ar')?'ar':'en'),role=null,challenge=null,activeCategory='',shown=24,lastQueryKey='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function t(k,vars={}){let v=(UI[lang]&&UI[lang][k])||UI.en[k]||k;Object.entries(vars).forEach(([a,b])=>v=v.replace(`{${a}}`,b));return v}
function txt(en,ar){if(lang==='ar')return ar||en;if(lang==='both')return`${en}<br><span class="translation">${ar||''}</span>`;return en}
function currentRoleLabel(){if(!role)return'';return lang==='ar'?ROLES[role].ar[0]:ROLES[role].en[0]}
function currentChallengeLabel(){if(!challenge)return'';return lang==='ar'?CHALLENGES[challenge].ar[0]:CHALLENGES[challenge].en[0]}
function applyLang(){document.documentElement.lang=lang==='ar'?'ar':'en';document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('msa_lang',lang);$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));$$('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));$('#search').placeholder=t('search');renderRoles();if(role)renderChallenges();if(role&&challenge)renderResults();renderCategoryChips();renderLibrary(true);updateLabLink()}
function renderRoles(){const box=$('#roleCards');box.innerHTML='';Object.entries(ROLES).forEach(([id,r])=>{const b=document.createElement('button');b.className='role-card'+(role===id?' selected':'');b.innerHTML=`<span class="role-icon">${r.icon}</span><strong>${txt(r.en[0],r.ar[0])}</strong><span>${txt(r.en[1],r.ar[1])}</span>`;b.onclick=()=>{role=id;challenge=null;renderRoles();renderChallenges();$('#challengeSection').classList.remove('hidden');$('#resultsSection').classList.add('hidden');$('#challengeSection').scrollIntoView({behavior:'smooth',block:'start'})};box.appendChild(b)})}
function renderChallenges(){const box=$('#challengeCards');box.innerHTML='';(ROLE_CHALLENGES[role]||Object.keys(CHALLENGES)).forEach(id=>{const c=CHALLENGES[id];const b=document.createElement('button');b.className='challenge-card'+(challenge===id?' selected':'');b.innerHTML=`<strong>${txt(c.en[0],c.ar[0])}</strong><span>${txt(c.en[1],c.ar[1])}</span>`;b.onclick=()=>{challenge=id;renderChallenges();renderResults();$('#resultsSection').classList.remove('hidden');$('#resultsSection').scrollIntoView({behavior:'smooth',block:'start'})};box.appendChild(b)})}
function allServices(){return DATA.categories.flatMap(c=>c.services.map(s=>({...s,category_en:c.category_en,category_ar:c.category_ar,category_id:c.id})))}
function isLab(s){return /problem-solving labs|advisory workshops/i.test(s.title_en)}
function scoreService(s){let score=0;if((s.roles||[]).includes(role))score+=3;if((s.challenges||[]).includes(challenge))score+=6;if(isLab(s)&&['capacity','process','bids','procurement','commercial'].includes(challenge))score+=5;if(challenge==='delay'&&/recovery|delay|acceleration|corrective/i.test(s.title_en))score+=3;if(challenge==='bids'&&/tender|bid|pricing/i.test(s.title_en))score+=2;return score}
function contactText(s){const title=lang==='ar'?s.title_ar:s.title_en;const url=location.href.split('#')[0];if(lang==='ar')return`مرحبًا م. محمد،\nأرغب في مناقشة خدمة: ${title}\nنوع الجهة: ${currentRoleLabel()||'—'}\nالتحدي الحالي: ${currentChallengeLabel()||'—'}\nرابط الخدمة: ${url}\n\nالاسم / الشركة: \nرقم التواصل: `;return`Hello Mohamed,\nI would like to discuss: ${title}\nOrganization: ${currentRoleLabel()||'—'}\nCurrent challenge: ${currentChallengeLabel()||'—'}\nService explorer: ${url}\n\nName / company: \nContact number: `}
function waLink(s){const phone=String(DATA.profile.ksa_whatsapp||'').replace(/\D/g,'');return`https://wa.me/${phone}?text=${encodeURIComponent(contactText(s))}`}
function emailLink(s){const title=lang==='ar'?s.title_ar:s.title_en;const subject=lang==='ar'?`استفسار استشاري - ${title}`:`Advisory enquiry - ${title}`;return`mailto:${DATA.profile.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(contactText(s))}`}
function serviceCard(s,{modal=false}={}){const signature=isLab(s);return`<article class="service-card${signature?' signature':''}"><span class="service-tag">${signature?`${lang==='ar'?'خدمة مميزة':'Signature Service'} · `:''}${txt(s.category_en,s.category_ar)}</span><h3 id="${modal?'modalTitle':''}">${txt(s.title_en,s.title_ar)}</h3><div class="info-block"><b>${t('struggle')}</b>${txt(s.pain_en,s.pain_ar)}</div><div class="info-block outcome"><b>${t('change')}</b>${txt(s.outcome_en,s.outcome_ar)}</div>${modal?`<div class="service-scope"><b>${t('details')}</b><p>${txt(s.scope_en,s.scope_ar)}</p></div>`:`<details class="service-scope"><summary>${t('details')}</summary><p>${txt(s.scope_en,s.scope_ar)}</p></details>`}<div class="service-actions"><a class="mini wa" href="${waLink(s)}" target="_blank" rel="noopener">${t('discuss')}</a><a class="mini" href="${emailLink(s)}">${t('email')}</a></div></article>`}
function renderResults(){if(!DATA||!challenge)return;const c=CHALLENGES[challenge];$('#resultTitle').innerHTML=txt(c.en[0],c.ar[0]);$('#resultSub').innerHTML=txt(c.en[1],c.ar[1]);const matches=allServices().filter(s=>(s.roles||[]).includes(role)&&(s.challenges||[]).includes(challenge)).sort((a,b)=>scoreService(b)-scoreService(a));$('#serviceResults').innerHTML=matches.slice(0,5).map(s=>serviceCard(s)).join('')||`<p>${t('noResults')}</p>`}
function renderCategoryChips(){if(!DATA)return;const box=$('#categoryChips');const cats=[{id:'',category_en:'All categories',category_ar:'كل المجالات'},...DATA.categories];box.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='category-chip'+(activeCategory===c.id?' active':'');b.textContent=lang==='ar'?c.category_ar:c.category_en;b.onclick=()=>{activeCategory=c.id;shown=24;renderCategoryChips();renderLibrary(true)};box.appendChild(b)})}
function filteredServices(){const q=($('#search').value||'').toLowerCase().trim();let list=allServices();if(activeCategory)list=list.filter(s=>s.category_id===activeCategory);if(q)list=list.filter(s=>[s.title_en,s.title_ar,s.scope_en,s.scope_ar,s.pain_en,s.pain_ar,s.outcome_en,s.outcome_ar].join(' ').toLowerCase().includes(q));return list}
function renderLibrary(reset=false){if(!DATA)return;const key=`${$('#search').value}|${activeCategory}|${lang}`;if(reset||key!==lastQueryKey){shown=24;lastQueryKey=key}const list=filteredServices();const visible=list.slice(0,shown);$('#libraryGrid').innerHTML=visible.map(s=>`<article class="library-card" role="button" tabindex="0" data-service-id="${s.id}"><small>${txt(s.category_en,s.category_ar)}</small><b>${txt(s.title_en,s.title_ar)}</b><span>${txt(s.pain_en,s.pain_ar)}</span></article>`).join('')||`<p>${t('noResults')}</p>`;$('#libraryCount').textContent=t('showing',{shown:visible.length,total:list.length});const remaining=Math.max(0,list.length-visible.length);const more=$('#libraryMore');more.hidden=remaining===0;if(remaining)more.textContent=t('showMore',{remaining})}
function openService(id){const s=allServices().find(x=>x.id===id);if(!s)return;$('#modalContent').innerHTML=serviceCard(s,{modal:true});$('#serviceModal').classList.remove('hidden');document.body.classList.add('modal-open');$('#modalClose').focus()}
function closeModal(){$('#serviceModal').classList.add('hidden');document.body.classList.remove('modal-open')}
function resetDiagnostic(){role=null;challenge=null;$('#challengeSection').classList.add('hidden');$('#resultsSection').classList.add('hidden');renderRoles();$('#diagnostic').scrollIntoView({behavior:'smooth'})}
function updateLabLink(){if(!DATA)return;const dummy={title_en:'Interactive Advisory Workshops & Live Problem-Solving Labs',title_ar:'ورش استشارية تفاعلية ومختبرات مباشرة لحل مشكلات العمل'};$('#labsContact').href=waLink(dummy)}
async function loadData(){const b64=(window.__SD||[]).join('');const bin=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if('DecompressionStream'in window){const ds=new DecompressionStream('gzip');return JSON.parse(await new Response(new Blob([bin]).stream().pipeThrough(ds)).text())}throw new Error('Browser does not support compressed data loading')}
async function init(){DATA=await loadData();$('#linkedinLink').href=DATA.profile.linkedin;$('#ksaWa').href='https://wa.me/'+String(DATA.profile.ksa_whatsapp).replace(/\D/g,'');$('#egyptWa').href='https://wa.me/'+String(DATA.profile.egypt_whatsapp).replace(/\D/g,'');$$('.lang-btn').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;applyLang()});$('#search').addEventListener('input',()=>renderLibrary(true));$('#libraryMore').onclick=()=>{shown+=24;renderLibrary(false)};$('#libraryGrid').addEventListener('click',e=>{const c=e.target.closest('[data-service-id]');if(c)openService(c.dataset.serviceId)});$('#libraryGrid').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-service-id]')){e.preventDefault();openService(e.target.dataset.serviceId)}});$('#modalClose').onclick=closeModal;$('#serviceModal').addEventListener('click',e=>{if(e.target===$('#serviceModal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#serviceModal').classList.contains('hidden'))closeModal()});$('#resetBtn').onclick=resetDiagnostic;renderCategoryChips();applyLang();updateLabLink()}
init().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend','<div style="position:fixed;bottom:12px;left:12px;right:12px;background:#8b1e2d;color:#fff;padding:12px;border-radius:12px;z-index:300">Site data could not load. Please refresh the page.</div>')});
